name: Test on push
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current version of the code
        uses: actions/checkout@master
      - name: Install python version 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pytest
        run: pip install pytest
      - name: Run the tests
        run: python -m pytest