name: Build documentation and publish the package on PyPI
on:
  push:
    tags:
      - v*


jobs:
  call-test:
    uses: galatolofederico/weirdcipher/.github/workflows/test.yaml@main
  
  build-documentation:
    runs-on: ubuntu-latest
    needs: call-test
    steps:
      - name: Checkout the current version of the code
        uses: actions/checkout@master
      - name: Install python version 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install sphinx and the theme
        run: pip install sphinx sphinx-rtd-theme
      - name: Build the documentation
        run: |
          cd sphinx-docs
          make html
      - name: Deploy on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: sphinx-docs/build/html
      
  publish-package:
    runs-on: ubuntu-latest
    needs: call-test
    steps:
      - name: Checkout the current version of the code
        uses: actions/checkout@master
      - name: Install python version 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install
        run: python -m pip install build --user
      - name: Build binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ . 
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}